# Generated by Django 3.2.7 on 2021-12-07 08:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Educator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('number', models.CharField(max_length=11, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Педагог',
                'verbose_name_plural': 'Педагоги',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата занятия')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='Время занятия')),
                ('educator_id', models.ManyToManyField(db_column='Педагог', to='main1.Educator')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('number', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now, verbose_name='Дата рождения')),
                ('skill_level', models.CharField(choices=[('1', 'Начинающий'), ('2', 'Продлжающий'), ('3', 'профессионал')], max_length=1, verbose_name='Уровень подготовки')),
            ],
            options={
                'verbose_name': 'Танцор',
                'verbose_name_plural': 'Танцоры',
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dance_style', models.CharField(max_length=50, verbose_name='Стиль танца')),
                ('skill_level', models.CharField(choices=[('1', 'Начинающий'), ('2', 'Продлжающий'), ('3', 'профессионал')], max_length=1, verbose_name='Уровень подготовки')),
            ],
            options={
                'verbose_name': 'Группа по направлениям',
                'verbose_name_plural': 'Группы по напарвлениям',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_lessons', models.CharField(max_length=50, verbose_name='Количество занятий')),
                ('price', models.CharField(max_length=50, verbose_name='Цена')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main1.style', verbose_name='Группа')),
                ('manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main1.manager', verbose_name='Менеджер')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main1.student', verbose_name='Танцор')),
            ],
            options={
                'verbose_name': 'Абонимент',
                'verbose_name_plural': 'Абонименты',
            },
        ),
        migrations.CreateModel(
            name='User11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30, verbose_name='Логин')),
                ('password', models.CharField(default='', max_length=300, verbose_name='Пароль')),
                ('privilegies', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presence', models.BooleanField(default=0, verbose_name='Присутствие')),
                ('schedule_id', models.ForeignKey(db_column='Занятие', on_delete=django.db.models.deletion.CASCADE, to='main1.schedule')),
                ('student_id', models.ForeignKey(db_column='Танцор', on_delete=django.db.models.deletion.CASCADE, to='main1.student')),
                ('subscription_id', models.ForeignKey(db_column='Абонемент', on_delete=django.db.models.deletion.CASCADE, to='main1.subscription')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='user_id',
            field=models.ForeignKey(db_column='Учетная запись', on_delete=django.db.models.deletion.CASCADE, to='main1.user11'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='group_id',
            field=models.ForeignKey(db_column='Группа', on_delete=django.db.models.deletion.CASCADE, to='main1.style'),
        ),
        migrations.AddField(
            model_name='manager',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main1.user11'),
        ),
    ]
